language: go
go:
- 1.13.x
go_import_path: github.com/corneliusweig/krew-index-tracker
notifications:
  email: false
before_install:
- go mod download
script:
- make lint
- make test
- make
- tar czf linux-amd64.tar.gz krew-index-tracker LICENSE
